#!/usr/bin/env bash
# docs/api/generate-cli-reference.sh
#
# Scaffolds the CLI reference skeleton by parsing src/bin/eco case branches
# and src/recipes/*.sh DESC/INPUTS/OUTPUT annotations.
# Output: docs/api/cli-reference.md
#
# IMPORTANT: The AWK parser for the eco router produces a skeletal subcommand
# table only — hand-verify and extend the output before committing, as the case
# branch pattern is not reliably machine-parseable. The canonical reference is
# maintained by hand in docs/api/cli-reference.md; run this script only when
# bootstrapping from scratch or after large structural changes to src/bin/eco.
#
# Usage:
#   bash docs/api/generate-cli-reference.sh

# shellcheck disable=SC2129 # Sequential section appends keep the scaffold readable.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_ROOT/docs/api/cli-reference.md"

cat >"$OUT" <<'HEADER'
# CLI Reference

> Skeleton generated by `docs/api/generate-cli-reference.sh` — hand-verify and
> extend before committing. See the script header for important caveats.

---

HEADER

# ── eco subcommands ─────────────────────────────────────────────────────────
{
  echo "## \`eco\` — CLI Router"
  echo ""
  echo "The main entry point. Routes subcommands to recipes, scheduler, and"
  echo "built-in operations."
  echo ""
  echo '```'
  echo "eco [<subcommand>] [args...]"
  echo '```'
  echo ""
  echo "### Subcommands"
  echo ""
  echo "| Command | Description |"
  echo "|---------|-------------|"

  # Parse eco router for subcommand cases
  if [[ -f "$REPO_ROOT/src/bin/eco" ]]; then
    awk '
      /^[[:space:]]+"?[a-z]/ && /\)/ {
        gsub(/[[:space:]]+/, "", $0)
        gsub(/\|/, " \\| ", $0)
        gsub(/\)/, "", $0)
        cmd = $0
      }
      /# / && cmd != "" {
        desc = $0
        sub(/.*# /, "", desc)
        printf "| `%s` | %s |\n", cmd, desc
        cmd = ""
      }
    ' "$REPO_ROOT/src/bin/eco" 2>/dev/null || true
  fi
  echo ""
} >>"$OUT"

# ── Recipes catalog ────────────────────────────────────────────────────────
{
  echo "---"
  echo ""
  echo "## Recipes"
  echo ""
  echo "Each recipe is a standalone script under \`src/recipes/\`."
  echo ""
  echo "| Recipe | Description | Inputs | Output |"
  echo "|--------|-------------|--------|--------|"

  for recipe in "$REPO_ROOT"/src/recipes/*.sh; do
    [[ -f "$recipe" ]] || continue
    name="$(basename "$recipe" .sh)"
    desc=$(grep -m1 '^# DESC:' "$recipe" 2>/dev/null | sed 's/^# DESC:[[:space:]]*//' || echo "—")
    inputs=$(grep -m1 '^# INPUTS:' "$recipe" 2>/dev/null | sed 's/^# INPUTS:[[:space:]]*//' || echo "—")
    output=$(grep -m1 '^# OUTPUT:' "$recipe" 2>/dev/null | sed 's/^# OUTPUT:[[:space:]]*//' || echo "—")
    echo "| \`$name\` | $desc | $inputs | $output |"
  done
  echo ""
} >>"$OUT"

# ── Scheduler CLI ──────────────────────────────────────────────────────────
{
  echo "---"
  echo ""
  echo "## \`eco scheduler\` — Job Scheduler"
  echo ""
  echo "Quota-aware cross-project AI-job dispatcher."
  echo ""
  echo '```'
  echo "eco scheduler <subcommand>"
  echo '```'
  echo ""
  echo "### Subcommands"
  echo ""
  echo "| Command | Description |"
  echo "|---------|-------------|"
  echo "| \`status [--json]\` | Show queue depth and meter availability |"
  echo "| \`add --file <path>\` | Add jobs from a YAML file |"
  echo "| \`run-once [--max-jobs N]\` | Execute one dispatch tick (debug) |"
  echo "| \`drain [--max-ticks N] [--interval-s S]\` | Run until idle or fully gated |"
  echo "| \`tail [--id <job-id>]\` | Show most recent attempt log |"
  echo "| \`seed --dir <path>\` | Import mission YAML files from a directory |"
  echo "| \`cancel <job-id> [--force]\` | Cancel a pending or gated job |"
  echo ""
} >>"$OUT"

# ── Environment variables ─────────────────────────────────────────────────
{
  echo "---"
  echo ""
  echo "## Environment Variables"
  echo ""
  echo "See [\`.env.example\`](../../.env.example) for the full list with defaults."
  echo "Detailed reference: [\`docs/reference/environment-variables.md\`](../reference/environment-variables.md)."
  echo ""
} >>"$OUT"

echo "Generated: $OUT"
