name: Dependabot auto-merge

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge minor/patch updates
    if: github.actor == 'dependabot[bot]' && vars.DEPENDABOT_AUTOMERGE == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444e5e4fda8 # v2.4.0
        id: metadata

      - name: Auto-approve minor/patch
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
